targets:
  $default:
    builders:
      nameof_gen:
        enabled: true
        generate_for:
          exclude:
            - test
          include:
            - test/integration/*

builders:
  nameof_gen:
    import: "package:nameof_gen/src/builder.dart"
    builder_factories: ["nameofGen"]
    build_extensions: { ".dart": [".nameof.dart"] }
    auto_apply: dependents
    build_to: source